//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session_Log
    {
        public decimal SessionNumber { get; set; }
        public decimal ID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Correct { get; set; }
        public decimal Skips { get; set; }
        public decimal Cards_Used { get; set; }
    
        public virtual Demographic Demographic { get; set; }
    }
}
